// import './globals.css'
import { getCssText, globalStyles } from '@/stitches.config'
import type { Metadata } from 'next'
import { Lexend, Raleway } from 'next/font/google'

const lexend = Lexend({ 
  weight: ['300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-lexend',
  subsets: ['latin'],
 })

 const raleway = Raleway({ 
  weight: ['300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-raleway',
  subsets: ['latin'],
 })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  globalStyles()

  return (
    <html lang="pt-br">
      <head>
        <style id="stitches" dangerouslySetInnerHTML={{ __html: getCssText() }} />
      </head>
      <body className={`${lexend.variable} ${raleway.variable}`}>{children}</body>
    </html>
  )
}
